In [1]:
from selenium import webdriver
import time
import pandas as pd
import os

from selenium.webdriver.support.select import Select
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

In [2]:
url1 = 'https://www.linkedin.com/login'

In [3]:
mail = 'enter your linkedin email/username'
password = 'enter your linkedin password'

In [4]:
service = Service(ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)
driver.get(url1)
driver.implicitly_wait(10)

In [5]:
driver.find_element(By.XPATH,"//input[@type='text']").send_keys(mail)
driver.find_element(By.XPATH,"//input[@type='password']").send_keys(password)
driver.find_element(By.XPATH,"//button[@class='btn__primary--large from__button--floating']").click()

In [6]:
url2 = 'https://www.linkedin.com/jobs/search/?currentJobId=3970858637&keywords=analyst&location=Dhaka%2C%20Bangladesh&origin=JOBS_HOME_SEARCH_BUTTON&refresh=true'

In [7]:
driver.get(url2)

In [11]:
import pandas as pd

ljob_title = []
lcompany_name = []
ljob_location = []
lposted_on = []
ljob_desc = []
lnum_app = []

In [12]:
# jobs = driver.find_elements(By.XPATH, "//ul[@class='scaffold-layout__list-container']/li")

# for job in jobs:
#     driver.execute_script("arguments[0].scrollIntoView();", job)
#     time.sleep(1)
    
# links = driver.find_elements(By.XPATH,"//ul[@class='scaffold-layout__list-container']/li")
# for link in links:
#     link.click()
#     time.sleep(3)
#     job_title = driver.find_element(By.XPATH,"//h1[@class='t-24 t-bold inline']").text
#     #job_location = driver.find_element(By.XPATH,"//body/div[@class='application-outlet']/div[@class='authentication-outlet']/div[4]/div[1]/div[1]/main[1]/div[1]/div[2]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/span[1]").text
#     company_name = driver.find_element(By.XPATH, "//div[@class='job-details-jobs-unified-top-card__company-name']").text
#     posted_on = driver.find_element(By.XPATH,"//span[@class='tvm__text tvm__text--low-emphasis'][3]").text
#     #job_desc = driver.find_element(By.XPATH, "//h2[@class='text-heading-large']//div[@class='mt4']").text
#     num_app = driver.find_element(By.XPATH,"//span[@class='tvm__text tvm__text--low-emphasis'][3]").text
    
#     ljob_title.append(job_title)
#     lcompany_name.append(company_name)
#     ljob_location.append(job_location)
#     lposted_on.append(posted_on)
#     #ljob_desc.append(job_desc)
#     lnum_app.append(num_app)

In [13]:
jobs = driver.find_elements(By.XPATH, "//ul[@class='scaffold-layout__list-container']/li")

for job in jobs:
    driver.execute_script("arguments[0].scrollIntoView();", job)
    time.sleep(1)
    
links = driver.find_elements(By.XPATH,"//ul[@class='scaffold-layout__list-container']/li")
for link in links:
    link.click()
    time.sleep(3)
    job_title = driver.find_element(By.XPATH,"//h1[@class='t-24 t-bold inline']").text
    job_location = driver.find_element(By.XPATH,"//div[@class='artdeco-entity-lockup__caption ember-view']").text
    company_name = driver.find_element(By.XPATH, "//div[@class='job-details-jobs-unified-top-card__company-name']").text
    posted_on = driver.find_element(By.XPATH,"//div[1]//div[1]//main[1]//div[1]//div[2]//div[2]//div[1]//div[2]//div[1]//div[1]//div[1]//div[1]//div[1]//div[1]//div[1]//div[3]//div[1]//span[3]").text
    #job_desc = driver.find_element(By.XPATH, "//h2[@class='text-heading-large']//div[@class='mt4']").text
    num_app = driver.find_element(By.XPATH,"//div[1]//div[1]//main[1]//div[1]//div[2]//div[2]//div[1]//div[2]//div[1]//div[1]//div[1]//div[1]//div[1]//div[1]//div[1]//div[3]//div[1]//span[5]").text
    
    ljob_title.append(job_title)
    lcompany_name.append(company_name)
    ljob_location.append(job_location)
    lposted_on.append(posted_on)
    #ljob_desc.append(job_desc)
    lnum_app.append(num_app)

In [15]:
print("Job Title:", len(ljob_title))
print("Company Name:", len(lcompany_name))
print("Job Location:", len(ljob_location))
print("Posted On:", len(lposted_on))
print("Number of Applicants:", len(lnum_app))

Job Title: 25
Company Name: 25
Job Location: 25
Posted On: 25
Number of Applicants: 25

In [16]:
print(ljob_location)

['Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)', 'Dhaka, Dhaka, Bangladesh (On-site)']

In [17]:
data = {
    "Job Title": ljob_title,
    "Company Name": lcompany_name,
    "Job Location": "Dhaka, Bangladesh",
    "Posted On": lposted_on,
#     "Job Description": ljob_desc,
    "Number of Applicants ": lnum_app
}

newdf = pd.DataFrame(data)

In [18]:
newdf

,Job Title,Company Name,Job Location,Posted On,Number of Applicants
0,Data Scientist- (For Gildan-G.A.B. Limited) - ...,Bdjobs.com,"Dhaka, Bangladesh",2 weeks ago,Over 100 applicants
1,Oracle Database Administrator,4P Marketing Consultancy,"Dhaka, Bangladesh",2 weeks ago,60 applicants
2,Data Scientist,Gildan,"Dhaka, Bangladesh",2 weeks ago,Over 100 applicants
3,Data Engineer,Data Crafters,"Dhaka, Bangladesh",1 week ago,41 applicants
4,Executive/Sr. Executive - ICT (ERP) - For A Re...,Bdjobs.com,"Dhaka, Bangladesh",2 weeks ago,9 applicants
5,Executive/ Sr. Executive - Performance Managem...,Bdjobs.com,"Dhaka, Bangladesh",3 weeks ago,5 applicants
6,Analyst,Nahee SS Pipes Industries Limited,"Dhaka, Bangladesh",1 week ago,45 applicants
7,Immunization Consultant,PATH,"Dhaka, Bangladesh",3 weeks ago,81 applicants
8,AI Software QA Tester,AIDevStudio.ai,"Dhaka, Bangladesh",Reposted 1 week ago,Over 100 applicants
9,Software Engineer for AI Training Data (Swift),G2i Inc.,"Dhaka, Bangladesh",4 days ago,20 applicants
10,Network Engineer-IT - For Best Tycoon (BD) Ent...,Bdjobs.com,"Dhaka, Bangladesh",3 weeks ago,94 applicants
11,Data Analyst,Talent Disruptors,"Dhaka, Bangladesh",4 months ago,0 applicants
12,"Analyst, Logistics(Freight Pay Origin-Panyu)",Centric Brands,"Dhaka, Bangladesh",4 days ago,44 applicants
13,Machine Learning Engineer,Alexa Translations,"Dhaka, Bangladesh",1 month ago,Over 100 applicants
14,Software Engineer for AI Training Data (Python),G2i Inc.,"Dhaka, Bangladesh",3 days ago,0 applicants
15,Associate Systems Engineer / Systems Engineer,MillenniumIT ESP,"Dhaka, Bangladesh",1 week ago,0 applicants
16,Python Developer - LLM Project,YO HR Consultancy,"Dhaka, Bangladesh",4 weeks ago,Over 100 applicants
17,Associate System Administrator,Therap (BD) Ltd.,"Dhaka, Bangladesh",6 months ago,0 applicants
18,Python Data Scientist - LLM Project,YO HR Consultancy,"Dhaka, Bangladesh",3 weeks ago,Over 100 applicants
19,Graduate Associate - Bangladesh,Standard Chartered,"Dhaka, Bangladesh",3 days ago,Over 100 applicants
20,Python Developer,Cerebital,"Dhaka, Bangladesh",4 months ago,0 applicants
21,Data Analyst,Clipboard Health,"Dhaka, Bangladesh",2 days ago,Over 100 applicants
22,Python Data Scientist/Analyst - LLM Project,YO HR Consultancy,"Dhaka, Bangladesh",1 month ago,Over 100 applicants
23,Software Engineer,Orbitax Bangladesh,"Dhaka, Bangladesh",2 weeks ago,Over 100 applicants
24,Jr. Software Project Coordinator - Dhaka,SJ Innovation LLC,"Dhaka, Bangladesh",3 weeks ago,0 applicants

In [19]:
newdf.to_csv("LinkedIn_Jobs.csv", index = True)